# Number of days of inactivity before an issue becomes stale
daysUntilStale: 100
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 30
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  An automated message from the stale bot -- this issue has been marked as stale
  because no comments have been made in 100 days. The goal of this action is to
  remind reporter and developers alike that progress seems to have stalled.
  Please note that the issue will be automatically closed 30 days from now,
  unless a comment is made, or the pinned label is applied.  Thank you.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: >
  An automated message from the stale bot -- this issue has been closed
  automatically, because no comments have been made in the 30 days since
  inactivity was first reported. It is easy to reopen issues, and both reporters
  and developers should feel free to do so, if warranted. It can help to add an
  informative comment during the reopening process.

